#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)

cd "$ROOT"
protoc \
  --proto_path=proto \
  --go_out=proto/gen/go \
  --go_opt=paths=source_relative \
  --dart_out=proto/gen/dart/lib/src \
  proto/seville/node/v2/node.proto \
  proto/seville/nodes/v1/tree.proto \
  proto/seville/notification/v1/notification.proto \
  proto/seville/system/v1/system.proto
