syntax = "proto3";

package seville.nodes.v1;

option go_package = "github.com/Matey2010/seville/proto/gen/go/seville/nodes/v1;nodesv1";

import "seville/node/v2/node.proto";

enum NodeRelationshipType {
  NODE_RELATIONSHIP_TYPE_UNSPECIFIED = 0;
  NODE_RELATIONSHIP_TYPE_PART_OF = 1;
  NODE_RELATIONSHIP_TYPE_FAMILY = 2;
}

enum NodeParameterType {
  NODE_PARAMETER_TYPE_UNSPECIFIED = 0;
  NODE_PARAMETER_TYPE_NAME = 1;
  NODE_PARAMETER_TYPE_ID = 2;
  NODE_PARAMETER_TYPE_PATH = 3;
  NODE_PARAMETER_TYPE_TITLE = 4;
  NODE_PARAMETER_TYPE_TAG = 5;
  NODE_PARAMETER_TYPE_LABEL = 6;
  NODE_PARAMETER_TYPE_SLUG = 7;
}

enum NodeSearchMatchOperator {
  NODE_SEARCH_MATCH_OPERATOR_UNSPECIFIED = 0;
  NODE_SEARCH_MATCH_OPERATOR_EXACT = 1;
  NODE_SEARCH_MATCH_OPERATOR_REGULAR_EXPRESSION = 2;
  NODE_SEARCH_MATCH_OPERATOR_STARTS_WITH = 3;
  NODE_SEARCH_MATCH_OPERATOR_ENDS_WITH = 4;
  NODE_SEARCH_MATCH_OPERATOR_CONTAINS = 5;
}

enum NodeSearchMatchMode {
  NODE_SEARCH_MATCH_MODE_UNSPECIFIED = 0;
  NODE_SEARCH_MATCH_MODE_ANY = 1;
  NODE_SEARCH_MATCH_MODE_ALL = 2;
}

message NodeSearchParameter {
  NodeParameterType parameter = 1;
  NodeSearchMatchOperator operator = 2;

  oneof value {
    string string_value = 3;
  }
}

message NodeSearchFilter {
  repeated NodeSearchParameter include_nodes_matching = 1;
  repeated NodeSearchParameter exclude_nodes_matching = 2;
  NodeSearchMatchMode include_match_mode = 3;
  bool negated = 4;
}

message NodeSearchQuery {
  NodeSearchFilter node_filter = 1;
  optional uint32 limit = 2;
}

message NodeSearchResult {
  repeated seville.node.v2.Node nodes = 1;
}

message NodeCreateRequest {
  string slug = 1;
  repeated string labels = 2;
}

message NodePropertyValue {
  oneof value {
    string string_value = 1;
    int64 integer_value = 2;
    double double_value = 3;
    bool boolean_value = 4;
  }
}

message NodeMutationRequest {
  NodeSearchFilter node_filter = 1;
  map<string, NodePropertyValue> set_properties = 2;
  repeated string remove_properties = 3;
}

message NodeMutationResult {
  uint64 mutated_node_count = 1;
}

message NodeTreeQuery {
  optional string root_node_id = 1;
  optional uint32 depth = 2;
  NodeRelationshipType traverse_by = 3;
  optional NodeSearchFilter node_filter = 4;
  optional NodeSearchFilter root_node_filter = 5;
}

message NodeTreeOccurrence {
  string occurrence_id = 1;
  optional string parent_occurrence_id = 2;
  uint32 depth = 3;
  seville.node.v2.Node node = 4;
}

message NodeTree {
  string root_node_id = 1;
  NodeRelationshipType relationship = 2;
  uint32 depth = 3;
  repeated NodeTreeOccurrence occurrences = 4;
}
